### ISSUE TITLE
Add an check option to release script

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/empty#13]
Release script will make some checks; but when creating the release... If version bump has been missed fr exmaple, it's too late.

A check option that will not create the release would be usefull to check *before* branhs/tags have been pushed, if developer whishes.

**Comment by orthagh** [comment]
For reference, with avh version of git flow:
https://github.com/petervanderdoes/gitflow-avh/blob/develop/hooks/pre-flow-hotfix-finish
