### ISSUE TITLE
Create simple crud n plugin glpi?

### ISSUE THREAD

**Issue by Renaldy27** [pluginsGLPI/empty#23]
How to create plugin in glpi with simple crud?

**Comment by trasher** [comment]
[Developper documentation](http://glpi-developer-documentation.readthedocs.io/en/master/plugins/index.html) may help you.
Use forums, IRC or mailing lists to get further help.

**Comment by Renaldy27** [comment]
Yes Create GLPI Plugins can you help me for step by step to create plugin glpi.
Because in documentation i'm not understand on this documentation
Thanks

**Comment by trasher** [comment]
"empty" plugin is a way to improve basic plugin creation; nothing more.
You'd better ask on the forums to get help. Or just see existing plugins to see how they work.

**Comment by Renaldy27** [comment]
Ok i'm try create plugin in documentation with empty plugin in github.

**Comment by Renaldy27** [comment]
Whats wrong this script ?
- Error during the database query: CREATE TABLE `glpi_plugin_agentless_configs` ( `id` INT(11) NOT NULL autoincrement, `name` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci - Error is You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `name` VARCHAR(255) NOT NULL, PRIMARY KEY' at line 2

**Comment by Renaldy27** [comment]
I'm try create plugin and not success, why whats wrong?
Setup.php
`<?php

define('PLUGIN_AGENTLESS_VERSION', '1.0');

function plugin_init_agentless() {
   global $PLUGIN_HOOKS;

   //required!
   $PLUGIN_HOOKS['csrf_compliant']['agentless'] = true;

   //some code here, like call to Plugin::registerClass(), populating PLUGIN_HOOKS, ...
}

/**
 * Get the name and the version of the plugin - Needed
 *
 * @return array
 */
function plugin_version_agentless() {
   return [
      'name'           => 'Agentless',
      'version'        => PLUGIN_AGENTLESS_VERSION,
      'author'         => '',
      'license'        => '',
      'homepage'       => '',
      'requirements'   => [
         'glpi'   => [
            'min' => '9.1'
         ]
      ]
   ];
}

/**
 * Optional : check prerequisites before install : may print errors or add to message after redirect
 *
 * @return boolean
 */
function plugin_agentless_check_prerequisites() {
   //do what the checks you want
   return true;
}

/**
 * Check configuration process for plugin : need to return true if succeeded
 * Can display a message only if failure and $verbose is true
 *
 * @param boolean $verbose Enable verbosity. Default to false
 *
 * @return boolean
 */
function plugin_agentless_check_config($verbose = false) {
   if (true) { // Your configuration check
      return true;
   }

   if ($verbose) {
      echo "Installed, but not configured";
   }
   return false;
}`

hook.php
`<?php

function plugin_agentless_install() {
   global $DB;

   //instanciate migration with version
   $migration = new Migration(100);

   //Create table only if it does not exists yet!
   if (!TableExists("glpi_plugin_agentless_agentlesss")) {
      $query = "CREATE TABLE `glpi_plugin_agentless_agentlesss` (
                  `id` int(11) NOT NULL auto_increment,
                  `name` varchar(255) collate utf8_unicode_ci default NULL,
                PRIMARY KEY (`id`)
               ) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";

      $DB->query($query) or die("error creating glpi_plugin_agentless_agentlesss ". $DB->error());
   }

   if (TableExists('glpi_plugin_agentless_configs')) {
      //missed value for configuration
      $migration->addField(
         'glpi_plugin_agentless_configs',
         'value',
         'string'
      );

      $migration->addKey(
         'glpi_plugin_agentless_configs',
         'name'
      );
   }

   //execute the whole migration
   $migration->executeMigration();

   return true;
}

function plugin_agentless_uninstall() {
   global $DB;

   $config = new Config();
   $config->deleteConfigurationValues('plugin:Agentless', array('configuration' => false));

   ProfileRight::deleteProfileRights(array('agentless:read'));

   $notif = new Notification();
   $options = array('itemtype' => 'Ticket',
                    'event'    => 'plugin_agentless',
                    'FIELDS'   => 'id');
   foreach ($DB->request('glpi_notifications', $options) as $data) {
      $notif->delete($data);
   }
   // Old version tables
   if (TableExists("glpi_plugin_agentless_agentlesss")) {
      $query = "DROP TABLE `glpi_plugin_agentless_agentlesss`";
      $DB->query($query) or die("error deleting glpi_plugin_agentless_agentlesss");
   }
   return true;
}`

front/agentless.from.php
`<?php
include ("../../../inc/includes.php");

// Check if plugin is activated...
$plugin = new Plugin();
if (!$plugin->isInstalled('agentlessplugin') || !$plugin->isActivated('agentlessplugin')) {
   Html::displayNotFoundError();
}

$object = new PluginAgentlessAgentless();

if (isset($_POST['add'])) {
   //Check CREATE ACL
   $object->check(-1, CREATE, $_POST);
   //Do object creation
   $newid = $object->add($_POST);
   //Redirect to newly created object form
   Html::redirect("{$CFG_GLPI['root_doc']}/agentless/front/agentless.form.php?id=$newid");
} else if (isset($_POST['update'])) {
   //Check UPDATE ACL
   $object->check($_POST['id'], UPDATE);
   //Do object update
   $object->update($_POST);
   //Redirect to object form
   Html::back();
} else if (isset($_POST['delete'])) {
   //Check DELETE ACL
   $object->check($_POST['id'], DELETE);
   //Put object in dustbin
   $object->delete($_POST);
   //Redirect to objects list
   $object->redirectToList();
} else if (isset($_POST['purge'])) {
   //Check PURGE ACL
   $object->check($_POST['id'], PURGE);
   //Do object purge
   $object->delete($_POST, 1);
   //Redirect to objects list
   Html::redirect("{$CFG_GLPI['root_doc']}/agentless/front/agentless.php");
} else {
   //per default, display object
   $withtemplate = (isset($_GET['withtemplate']) ? $_GET['withtemplate'] : 0;
   $object->display(
      [
         'id'           => $_GET['id'],
         'withtemplate' => $withtemplate
      ]
   );
}`
front/agentless.php
`<?php
include ("../../../inc/includes.php");

// Check if plugin is activated...
$plugin = new Plugin();
if (!$plugin->isInstalled('agentless') || !$plugin->isActivated('agentless')) {
   Html::displayNotFoundError();
}

//check for ACLs
if (PluginAgentlessAgentless::canView()) {
   //View is granted: display the list.

   //Add page header
   Html::header(
      __('agentless', 'agentless'),
      $_SERVER['PHP_SELF'],,
      'assets',
      'pluginagentlessagentless',
      'agentless'
   );

   Search::show('PluginAgentlessAgentless');

   Html::footer();
} else {
   //View is not granted.
   Html::displayRightError();
}`
inc/agentless.class.php
`<?php
class PluginAgentlessAgentless extends CommonDBTM {
   function showForm ($ID, $options=array()) {

      $this->initForm($ID, $options);

      $options['formoptions']
            = "onSubmit='return plugaddr_Check(\"".__('Invalid data !!', 'addressing')."\")'";
      $this->showFormHeader($options);

      $PluginAddressingConfig = new PluginAddressingConfig();
      $PluginAddressingConfig->getFromDB('1');

      echo "<tr class='tab_bg_1'>";

      echo "<td>".__('Name')."</td>";
      echo "<td>";
      Html::autocompletionTextField($this,"name");
      echo "</td>";

      echo "</tr>";


      if ($PluginAddressingConfig->fields["use_ping"]) {
         echo "<td>".__('Ping free Ip', 'addressing')."</td><td>";
         Dropdown::showYesNo('use_ping', $this->fields["use_ping"]);
         echo "</td>";
      } else {
         echo "<td>";
         echo Html::hidden('use_ping', array('value' => 0));
         echo "</td><td></td>";
         //echo "<td><input type='hidden' name='use_ping' value='0'></td><td></td>";
      }
      echo "</tr>";

      echo "<tr class='tab_bg_1'>";
      echo "<td>".__('First IP', 'addressing')."</td>"; // Subnet
      echo "<td>";
      echo "<input type='text' id='plugaddr_ipdeb0' value='' name='_ipdeb0' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipdeb1' value='' name='_ipdeb1' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipdeb2' value='' name='_ipdeb2' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipdeb3' value='' name='_ipdeb3' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>";
      echo "</td>";
      echo "<td></td>";
      echo "<td></td>";
      echo "</tr>";

      echo "<tr class='tab_bg_1'>";
      echo "<td>".__('Last IP', 'addressing')."</td>"; // Mask
      echo "<td>";
      echo "<input type='text' id='plugaddr_ipfin0' value='' name='_ipfin0' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipfin1' value='' name='_ipfin1' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipfin2' value='' name='_ipfin2' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>.";
      echo "<input type='text' id='plugaddr_ipfin3' value='' name='_ipfin3' size='3' ".
           "onChange='plugaddr_ChangeNumber(\"".__('Invalid data !!', 'addressing')."\");'>";
      echo "</td>";
      echo "<td></td>";
      echo "<td></td>";
      echo "</tr>";

      echo "<tr class='tab_bg_1'>";
      echo "<td>".__('Report for the IP Range', 'addressing')."</td>"; // Mask
      echo "<td>";
      echo "<input type='hidden' id='plugaddr_ipdeb' value='".$this->fields["begin_ip"]."' name='begin_ip'>";
      echo "<input type='hidden' id='plugaddr_ipfin' value='".$this->fields["end_ip"]."' name='end_ip'>";
      echo "<div id='plugaddr_range'>-</div>";
      if ($ID > 0) {
         $js = "plugaddr_Init(\"".__('Invalid data !!', 'addressing')."\");";
         echo Html::scriptBlock($js);
      }
      echo "</td>";
      echo "<td></td>";
      echo "<td></td>";
      echo "</tr>";

      echo "<tr class='tab_bg_1'>";

      echo "<td>".__('MAC Address')."</td>";
      echo "<td>";
      Html::autocompletionTextField($this,"name");
      echo "</td>";

      echo "</tr>";

      echo "<tr class='tab_bg_1'>";

      echo "<td>".__('Update On')."</td>";
      echo "<td>";
      Html::autocompletionTextField($this,"name");
      echo "</td>";

      echo "</tr>";

      $this->showFormButtons($options);

      return true;
   }
}`

**Comment by Renaldy27** [comment]
i create plugin but not running why?
