### ISSUE TITLE
Re-license `empty` to e.g. BSD for broader use

### ISSUE THREAD

**Issue by mikekaganski** [pluginsGLPI/empty#31]
Can the `empty` plugin, that is created to be a starting point for own plugin development, be please re-licensed from GPL to something permissive, e.g. BSD, to allow e.g. my plugin be MPLv2, etc. Up to now, the plugin has two contributors, so possibly this is doable (if conceptually acceptable)?

**Comment by cedric-anne** [comment]
Hi,

We switched to MIT license.

Regards

**Comment by mikekaganski** [comment]
Thank you very much! :-)
